name: Send a telegram message abount today's weather every morning

on:
  weather:
    apiKey: ${{ secrets.OPENWEATHERMAP_API_KEY }}
    params:
      lat: 59.8944
      lon: 30.2642
      units: metric
    every: 0
    timeZone: UTC+3

jobs:
  notify:
    name: Send notifications
    runs-on: ubuntu-latest
    steps:
      - name: View context attributes
        uses: actions/github-script@v4
        with:
          script: |
            console.log(context)

      - name: Prepare a telegram message
        uses: actions/github-script@v4
        id: message
        env:
          WEATHER_DATA: ${{ toJSON(on.weather.outputs) }}
          CURRENT: ${{ toJSON(on.weather.outputs.current) }}
          WEATHER: ${{ toJSON(on.weather.outputs.current.weather[0]) }}
          DAILY_TEMPERATURE: ${{ toJSON(on.weather.outputs.daily[0].temp) }}
        with:
          script: |
            /**
             * Process env variables
             * @type {string[]}
             */
            const { WEATHER_DATA, CURRENT, WEATHER, DAILY_TEMPERATURE } = process.env

            /**
             * Side directions
             * @type {string[]}
             */
            const DIRECTIONS = ['north', 'north-west', 'west', 'south-west', 'south', 'south-east', 'east', 'north-east'];

            /**
             * Locale
             * @type {string}
             */
            const LOCALE = 'en-GB';

            /**
             * Date format
             * @type {{hour: string, timeZone: string, minute: string}}
             */
            const DATE_FORMAT = {
                hour: '2-digit',
                minute: '2-digit',
                timeZone: 'Europe/Moscow',
            };

            /**
            * Returns formatted side direction by input angle in degrees
            * @param angle initial input angle in degrees to calculate by
            * @returns {string} formatted side direction
            */
            const formatSideDirection = value => {
                return DIRECTIONS[Math.round(((value %= 360) < 0 ? value + 360 : value) / 45) % 8];
            };

            /**
            * Returns formatted date by input date/time pattern
            * @param value initial input date to format
            * @returns {string} short formatted date
            */
            const formatDateByPattern = value => {
              return new Date(value * 1000).toLocaleString(LOCALE, DATE_FORMAT);
            };

            console.log(JSON.stringify(WEATHER_DATA));

            const longitude = WEATHER_DATA.lon;
            const latitude = WEATHER_DATA.lat;
            const timezone = WEATHER_DATA.timezone;

            const main = WEATHER.main;
            const description = WEATHER.description;

            const tempMin = DAILY_TEMPERATURE.min;
            const tempMax = DAILY_TEMPERATURE.max;

            const temperature = Math.round(CURRENT.temp);
            const temperatureLike = Math.round(CURRENT.feels_like);
            const pressure = Math.round(CURRENT.pressure);
            const humidity = Math.round(CURRENT.humidity);
            const visibility = Math.round(CURRENT.visibility);
            const clouds = Math.round(CURRENT.clouds);
            const uvi = Math.round(CURRENT.uvi);

            const wind = Math.round(CURRENT.wind_speed);
            const windDirection = formatSideDirection(CURRENT.wind_deg);

            const sunrise = formatDateByPattern(CURRENT.sunrise);
            const sunset = formatDateByPattern(CURRENT.sunset);

            let result = '';
            result += `Currently, the weather in <= Saint-Petersburg => (lon: ${longitude}, lat: ${latitude}, timezone: ${timezone}) is:\n\n`;
            result += `temperature: ${temperature}°C [${tempMin}-${tempMax}°C] (${main}, ${description}), fells like ${temperatureLike}°C,\n`;
            result += `humidity: ${humidity}%,\n`;
            result += `pressure: ${pressure} (mbar),\n`;
            result += `visibility: ${visibility},\n`;
            result += `uvi: ${uvi},\n`;
            result += `wind: /${windDirection}/ ${wind} (m/s),\n`;
            result += `cloudy: ${clouds}%,\n\n`;
            result += `today, the Sun rises at ${sunrise}am and sets at ${sunset}pm.\n`;

            return result;
          result-encoding: string

      - name: Send a telegram message
        uses: appleboy/telegram-action@v0.1.0
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: ${{ steps.message.outputs.result }}
