name: Quotes

on:
  script:
    config:
      force: true
      skipSchedule: false
      manualRunEvent:
        - workflow_dispatch
        - push
    path: ./workflows/quotes.js

jobs:
  quotes:
    name: Send quotes
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          title: ${{ fromJSON(on.script.outputs).message }}
        run: |
          echo title: $title

#      - name: Send a telegram message
#        uses: appleboy/telegram-action@v0.1.0
#        with:
#          to: ${{ secrets.TELEGRAM_TO }}
#          token: ${{ secrets.TELEGRAM_TOKEN }}
#          message: ${{ fromJSON(on.script.outputs).message }}