name: Quotes

on:
  script:
    run: |
      return `<a href="https://styled-quotes.vercel.app/api?theme=buefy&layout=default">Styled Quotes</a>`

jobs:
  notify:
    name: Send notifications
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          data: ${{ on.script.outputs }}
        run: |
          echo >>>
          echo $data
          echo >>>

      - name: Prepare a telegram message
        uses: actions/github-script@v4
        id: message
        env:
          data: ${{ on.script.outputs }}
        with:
          script: |
            return `\n${data}\n`;
          result-encoding: string

      - name: Send a telegram message
        uses: appleboy/telegram-action@v0.1.0
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: ${{ steps.message.outputs.result }}
          format: html