name: RSS multiple data feeds

on:
  rss:
    url:
      - https://actionsflow.github.io/test-page/hn-rss.xml
      - https://www.buzzfeed.com/world.xml
      - https://www.theguardian.com/uk/rss
      - https://news.ycombinator.com/rss
      - https://www.computerworld.com/index.rss
      - https://www.informationweek.com/rss_simple.asp
      - https://www.infoworld.com/index.rss
      - https://www.computerweekly.com/rss/All-Computer-Weekly-content.xml
      - https://www.reddit.com/r/InformationTechnology/.rss?format=xml
      - https://www.itworldcanada.com/feed
      - https://devcases.com/feed/
      - https://plumbr.io/blog/feed
      - https://www.thejavaprogrammer.com/feed
      - https://nodesource.com/blog/rss
      - https://understanding-hadoop-by-mahesh.blogspot.com/feeds/posts/default?alt=rss
      - https://curatedsql.com/category/hadoop/feed/
      - https://kognitio.com/blog/category/kognitio-on-hadoop/feed/
      - http://www.hadoopinrealworld.com/blog/feed/
      - https://mobiledevmemo.com/feed/
      - https://androidsweets.ongoodbits.com/feed
      - https://gizmodo.com/tag/android/rss
      - https://medium.com/feed/tag/java
      - https://android-arsenal.com/rss
      - https://www.androidauthority.com/android-development/feed/
      - https://superkotlin.com/blog/feed/
      - https://talkingkotlin.com/feed
    config:
      limit: 200

jobs:
  notify:
    name: Send notifications
    runs-on: ubuntu-latest
    steps:
      - name: Prepare a telegram message
        uses: actions/github-script@v4
        id: message
        env:
          title: ${{ on.rss.outputs.title }}
          contentSnippet: ${{ on.rss.outputs.contentSnippet }}
          link: ${{ on.rss.outputs.link }}
        with:
          script: |
            /**
             * Process env variables
             * @type {string[]}
             */
            const { title, contentSnippet, link } = process.env

            let result = '';
            result += '---\n';
            result += `Title: ${title}\n\n`;
            result += `Content: ${contentSnippet}\n`;
            result += `Link: ${link}\n`;
            result += '---\n';

            return result;
          result-encoding: string

      - name: Send a telegram message
        uses: appleboy/telegram-action@v0.1.0
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: ${{ steps.message.outputs.result }}
