name: Scripting with file

on:
  script:
    config:
      limit: 10
    path: ./workflows/script.js

jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Script Outputs
        env:
          title: ${{on.script.outputs.title}}
        run: |
          echo title: $title