name: Styled Quotes

on:
  script:
    config:
      force: true
      skipSchedule: true
      manualRunEvent:
        - workflow_dispatch
        - push
    run: |
      return [{"message": "https://styled-screenshots.vercel.app/api?url=https://www.google.com/&width=450&height=250"}]
#      return [{"message": "https://styled-quotes.vercel.app/api?theme=buefy&layout=default"}]

#      const result = await helpers.axios.get(
#          "https://styled-quotes.vercel.app/api?theme=buefy&layout=default"
#      );
#
#      return [{"message": result.data}]

jobs:
  quotes:
    name: Styled quotes
    runs-on: ubuntu-latest
    steps:
      - name: Prepare a telegram message
        uses: actions/github-script@v4
        id: message
        env:
          outputs: ${{ toJson(on.script.outputs) }}
        with:
          script: |
            const { outputs } = process.env;

            console.log(JSON.stringify(outputs));

            return `[](${JSON.parse(outputs).message})`;

      - name: Send a telegram message
        uses: appleboy/telegram-action@v0.1.0
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: ${{ steps.message.outputs.result }}
          format: markdown
