name: Get Instagram data

on:
  instagram:
    config:
      active: false
    user_id: "17841432487737681"
    access_token: ${{ secrets.INSTAGRAM_ACCESS_TOKEN }}

jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          media_url: ${{ on.instagram.outputs.media_url }}
        run: |
          echo media_url: $media_url