name: RSS to Zapier

on:
  rss:
    url: https://actionsflow.github.io/test-page/hn-rss.xml
    config:
      active: false

jobs:
  ifttt:
    name: Make a Request to Zapier
    runs-on: ubuntu-latest
    steps:
      - uses: actionsflow/axios@v1
        with:
          url: https://hooks.zapier.com/hooks/catch/xxx
          method: POST
          data: '{ "name": "breeze",  "title": "${{on.rss.outputs.title}}" }'