name: Scripting with source

on:
  script:
    run: |
      const result = await helpers.axios.get("https://jsonplaceholder.typicode.com/posts")
      return result.data
    deduplicationKey: id

jobs:
  print:
    name: Print
    runs-on: ubuntu-latest
    steps:
      - name: Print Outputs
        env:
          title: ${{on.script.outputs.title}}
        run: |
          echo title: $title